### ISSUE TITLE
Ring Meister is a fixed series. Listed as open on the details page.

### ISSUE THREAD

**Issue by gscottolson** [popmonkey/irs#21]
Just a small data bug.

Thanks for creating and maintaining this resource. Super valuable.

**Comment by popmonkey** [comment]
> Just a small data bug.

oh yeah - interesting - it _was_ open in previous seasons so i think i'm not updating it correctly.  good find!

**Comment by popmonkey** [comment]
turns out there were some duplicate entries in the DB after a schema refactor I did in December.  this caused the incorrect row to be updated when iRacing changed the series from open to fixed

this probably was causing other subtle bugs

fixed now
